[project]
name = "vector-ai-agents-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.9.0",
    "crewai>=0.201.1",
    "crewai_tools",
    "isort>=6.0.1",
    "ruff>=0.13.2",
]
